title: RLEM Workshop - BuildSys'22
preposition: at
description: Third ACM SIGEnergy Workshop on Reinforcement Learning for Energy Management in Buildings & Cities (RLEM)
  >
  About RLEM
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rlem-workshop.net/" # the base hostname & protocol for your site, e.g. https://example.com

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# List of Important Days
important_dates:
  - name: "Abstract submission"
    date: "August 15, 2022 (AOE)"
  - name: "Paper submission"
    date: "August 22, 2022 (AOE)"
  - name: "Notifications"
    date: "September 9, 2022 (AOE)"
  - name: "Camera Ready"
    date: "September 16, 2022 (AOE)"
  - name: "Workshop date"
    date: "November 8, 2022"

# Organisation
organization:
  - role: "General"
    chair: true
    member:
      - name: "Zoltan Nagy"
        url: "https://nagy.caee.utexas.edu/team/prof-zoltan-nagy-phd/"
        affiliation: "University of Texas at Austin"
      - name: "Jan Drgona"
        url: "https://www.pnnl.gov/people/jan-drgona"
        affiliation: "Pacific Northwest National Laboratory"
  - role: "Technical Program Committee"
    chair: true
    member:
      - name: "Kuldeep Kurte"
        url: "https://www.ornl.gov/staff-profile/kuldeep-r-kurte"
        affiliation: "Oak Ridge National Laboratory"
      - name: "Matias Quintana"
        url: "https://matiasquintana.com/"
        affiliation: "National University of Singapore"
      - name: "Yaxin Bi"
        url: "https://www.ulster.ac.uk/staff/y-bi"
        affiliation: "Ulster University at Jordanstown"
  - role: "Web"
    chair: True
    member:
      - name: "Kingsley Nweye"
        url: "https://www.linkedin.com/in/kingsley-nweye-892074139/"
        affiliation: "University of Texas at Austin"
  - role: "Technical Program Committee"
    chair: false
    member:
 
conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: BuildSys'22
      # img: ''
      url: 'https://buildsys.acm.org/2022/'
    links:
      - name: Dates
        relative_url: /important/
      - name: CfP
        relative_url: /cfp/
      - name: Program
        relative_url: /program/
      - name: Speakers
        relative_url: /speakers/
      - name: Organisation
        relative_url: /organisation/
      - name: Location
        relative_url: /location/
      - name: Previous Editions
        menu:
          - name: 2022 (current)
            disabled: true
          # - name: 2021
          #   relative_url: /2021/
          # - name: 2020
          #   relative_url: /2020/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Important Dates
        relative_url: /important/
      - name: Call for Papers
        relative_url: /cfp/
      - name: Program
        relative_url: /program/
      - name: Organisation
        relative_url: /organisation/
      - name: How to get there
        relative_url: /location/

  # Information boxes
  info_bars:
    - title: Welcome to the RLEM Workshop!
      color: primary
      main_only: true
      text: |
        Call for papers is live and registration is coming soon!

    - text: Don't forget to check out the main conference BuildSys'22!
      color: warning
      pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: 47.37808, 8.53935
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: Cat A
        color: info
      - name: Cat B
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
